### PR TITLE
Add quaternion to cf tf

### PR DESCRIPTION
**Pull request by stephanbro**
In conjunction with the commit in the crazyflie-firmware repo, https://github.com/bitcraze/crazyflie-firmware/commit/ff15bbe9a4d30e6335d02528c26fa37d33097df2, this will give a full orientation for attaching sensors to the crazyflie in ROS.

Also adds namespaces to avoid publishing conflicts with multiple crazyflies.

### CODE REVIEW

**Comment by krichardsson** [comment]
Nice!
The code is violating flake8 guidelines though (see the travis build). Please fix so we can merge.

Thanks!

**Comment by ataffanel** [comment]
Thanks, this looks good. Though for me it breaks the anchor position upload in the ekf bridge, I get this error when launching dwm_loc_ekf_hover.launch:

```
[INFO] [WallTime: 1477427222.777714] Setting anchor position ...
[INFO] [WallTime: 1477427222.780757] Anchor 0 at [0.0, 0.0, 1.0]
[ INFO] [1477427222.791537043]: Update parameters
[ERROR] [1477427222.791629515]: Could not find param /crazyflie/anchorpos/anchor0x
[ERROR] [1477427222.791666387]: Could not find param /crazyflie/anchorpos/anchor0y
[ERROR] [1477427222.791699716]: Could not find param /crazyflie/anchorpos/anchor0z
```

I traced the problem to this line: https://github.com/bitcraze/lps-ros/pull/5/files#diff-910dab866d5ea4bd5521e26198c82c6bR73 in lps_ekf_bridge.py. Removing rospy.get_namespace() fixes the problem. Are you seeing something similar?

**Comment by stephanbro** [comment]
@ataffanel I am seeing the same issue. Looking at crazyflie_ros repo, the parameters get published with the tf_prefix, so they should be referencing the same path. I'm thinking the issue could be a race condition with the parameter not existing until the connection is established, but the anchor pos has already tried to set the appropriate parameters.

When you are connected, can you look at the output of `rosparam list` and see if everything makes sense with prefixes?

**Comment by stephanbro** [comment]
@ataffanel I was able to reproduce the issue you saw and made a fix in my latest commit. Have you had the chance to test it yet?

**Comment by ataffanel** [comment]
Finally got a chance to test it, looks great with the orientation in rviz, thanks!

**Pull request merged**
