### PR TITLE
Anchor pos viz

### PR DESCRIPTION
**Pull request by stephanbro**
This PR depends on whoenig/crazyflie_ros#49 and does the following:
* Change the anchorpos parameters to be only in the global namespace
* Change log type to a Float32MultiArray which allows much easier plotting of data (in rqt_plot for example), as it is encoded as floats instead of string of a literal list
* Only send anchor positions if it isn't already enabled on the crazyflie
* Add a visualization for TWR/TDMA to show the range estimate from each anchor

Should address #6.

### CODE REVIEW

**Comment by stephanbro** [comment]
@ataffanel have you had a chance to test this yet?

**Comment by ataffanel** [comment]
Hi, finally got around to test it. Looks good to me but I think we need to merge the crazyflie_ros change first to avoid breaking this repos.

**Comment by stephanbro** [comment]
@ataffanel were you able to get the visualization working? I haven't had a chance to fly recently, so I don't have a screenshot handy.

**Comment by ataffanel** [comment]
Ho, no I forgot to check the visualisation, I was flying with TDoA. I still need to check that. But the rest worked fine as soon as I updated the crazyflie ros driver to your PR branch.

**Comment by ataffanel** [comment]
I am closing this for the time being. Feel free to reopen with only the visualisation since this could be merged directly.

**Pull request closed without merging**
